Update GHES host check
actions/toolkit pull request #1648
Opened 2024-01-31 16:20 UTC by eggyhead

## What are we doing?
Currently, we are only checking equality against `github.com` to ensure artifact and cache actions are being run in a non-enterprise host. We need to update this check to allow requests from `ghe.com` and `ghe.localhost`, additional allowed hostnames for production and local development. 

Fixes https://github.com/github/actions-results-team/issues/2208

## How are we doing it?
- We are including the known GItHub hostnames in the _negative_ condition for `isGhes`

## How do I test?
- Run upload or download artifact from an allowed host using this toolkit package version

2024-01-31 17:49 UTC, yacaovsnc approved these changes

2024-01-31 18:33 UTC, merged

2024-04-02 12:57 UTC, chrisimap32 requested changes
R

2024-04-03 20:36 UTC, lawyoum commented on packages/cache/src/internal/cacheUtils.ts
> +  const isProximaHost = (hostname.endsWith('GHE.COM') || hostname.endsWith('GHE.LOCALHOST'))
???

2024-04-03 20:36 UTC, lawyoum commented on packages/cache/src/internal/cacheUtils.ts
> +  const isProximaHost = (hostname.endsWith('GHE.COM') || hostname.endsWith('GHE.LOCALHOST'))
> ## Incomplete URL substring sanitization
> 
> '[GHE.COM](1)' may be preceded by an arbitrary host name.
> 
> [Show more details](https://github.com/actions/toolkit/security/code-scanning/26)

2024-04-03 21:26 UTC, chrisimap32 commented
[](@chrisimap32 )